name: BaNBT
version: '${project.version}'
description: An addon for the BanItem plugin by Andross96. "https://www.spigotmc.org/resources/banitem-1-7-1-19.67701/"
author: Conorsmine
main: com.conorsmine.net.banbt.BaNBT
depend: [BanItem, NBTAPI]

commands:
  banbt:
    description: This acts as the main command for this plugin. All other commands are a subcommand of this.
    aliases: [bn]

permissions:
  banbt.*:
    description: Universal permission for all commands.
    children: [banbt.admin]

  banbt.admin:
    description: Same as "banbt.*"

  banbt.info:
    description: Displays the NBT-Data of the handheld item.

  banbt.reload:
    description: Reloads the plugin.